### ISSUE TITLE
make:entity make:entity --uuid or --uild as option 

### ISSUE THREAD

**Issue by jaures-kano** [symfony/maker-bundle#1037] opened 2021-12-17 09:04 UTC

**Comment by pakolkf** [comment] 2022-01-16 18:01
Hi, I have implemented this option but it is impossible for me to dump it to the main branch since it does not pass the tests. Any ideas? It is possible to speak Spanish @javiereguiluz

**Comment by jrushlow** [comment] 2024-02-16 14:25
Sorry for the slow response, @pakolkf - without a PR, it's impossible to tell what the problems could be.

Closing as a duplicate of #745

**Closed by jrushlow** 2024-02-16 14:25 UTC
Labels: Feature, HasPR, duplicate
