### ISSUE TITLE
make:entity unique property

### ISSUE THREAD

**Issue by AndrasZiegenham** [symfony/maker-bundle#244] opened 2018-08-10 11:49 UTC
Console command make:entity doesn't ask if I want the property to be unique and if I add it to the annotation manually, then continue adding new properties, it removes it... :/
I think it should either ask if I wanted unique, or at least keep my previous properties untouched.

**Comment by LeJeanbono** [comment] 2018-09-12 00:54
Something like : `@ORM\Column(name="email", type="string", length=255, unique=true)` could be ok for you ?
I can work on it.

**Comment by weaverryan** [comment] 2019-05-01 19:42
I don't think the `make:entity` command should ask if you want a unique column - it's just too rare of a question to ask for *every* single column. However, if you add it by hand and continue adding more properties, it should *not* remove it. Or are you adding it even before the command has finished running?

**Comment by jrushlow** [comment] 2021-02-17 08:59
I'm closing this issue for now as I'm unable to reproduce the problem locally. `make:entity` does not seem to remove properties or the `unique` annotation on modifying an entity that already has them. If you're still experiencing problems, please feel free to reopen / create a new issue. Thanks @AndrasZiegenham!

**Closed by jrushlow** 2021-02-17 08:59 UTC
Labels: Unconfirmed
