### ISSUE TITLE
make:entity always call ORM\Id  id

### ISSUE THREAD

**Issue by f4810** [symfony/maker-bundle#1408] opened 2023-12-11 09:14 UTC
Make a new entity always call `id` the autoincrement column because of [this template](https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/doctrine/Entity.tpl.php)

First, not all tables have a generated ID: the primary key may be differents (starting from mysql 8 they add the invisible indexes and id is even not mandatory!) like a couple (year,number ?) or a generated code or a UUID.

Second, ID is a SQL Antipattern. If you have many tables with ID as the id you are making reporting that much more difficult. It obscures meaning and makes complex queries harder to read as well as requiring you to use aliases to differentiate on the report itself.

My hint is at least to use something like  $<?= strtolower($table_name) ?>Id in that template or, better, to add a new Field type that specify the generated field (if there is one!).

**Comment by jrushlow** [comment] 2024-02-27 19:54
Duplicate of #745

**Closed by jrushlow** 2024-02-27 19:54 UTC
Labels: duplicate

**Comment by f4810** [comment] 2024-03-31 19:51
Now, #745 is completed and make:entity is still useless and we still must use only $id as orm\id ... 
so may be this issue isn't really a duplicate ? 

now, after 745, you can use UUID, or ULID, great... but even you will get:

    private ? **$id** = null;

and this is a problem, I think. Please consider reopen this issue. Thanks.
