### ISSUE TITLE
Doctrine - Optional feature $id as UUID instead of Integer when creating new entity

### ISSUE THREAD

**Issue by skocdopolet** [symfony/maker-bundle#1033] opened 2021-12-06 19:08 UTC
### Description

I am working on a new project in Symfony 5.3. I am using this command bin/console make:entity for creating entities.

This wizard automatically creates an entity with $id as primary key of type integer. I am prefering UUID instead of integer.

How I should change settings to get Entity like example?

### Example

namespace App\Entity;
    
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
    
/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private $id;
    
     ...
}

**Comment by skocdopolet** [comment] 2023-06-14 10:36
Hello, is there please some progress?  Thanks

**Comment by jrushlow** [comment] 2024-02-16 14:29
Duplicate of #745 - we'll have PR #1329 merge / released soon!

**Closed by jrushlow** 2024-02-16 14:29 UTC
Labels: Feature, HasPR, duplicate
