### ISSUE TITLE
make:entity property error Type::JSON_ARRAY

### ISSUE THREAD

**Issue by amberlex78** [symfony/maker-bundle#996] opened 2021-10-16 07:26 UTC
PHP Version 8.0.11
Symfony 5.3.9
doctrine/dbal (3.1.3)

I create entity
```
$ symfony console make:entity Post

 created: src/Entity/Post.php
 created: src/Repository/PostRepository.php
 
 Entity generated! Now let's add some fields!
 You can always add more fields later manually or by re-running this command.

 New property name (press <return> to stop adding fields):
 > title


In MakeEntity.php line 379:
                                                           
  Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY  
```
In `vendor/symfony/maker-bundle/src/Maker/MakeEntity.php` In string  378, 379
``` php
// remove deprecated json_array
unset($types[Type::JSON_ARRAY]);
```
but we no have this type in
```
vendor/doctrine/dbal/src/Types/
```

**Comment by tarlepp** [comment] 2021-10-16 09:19
Duplicate of https://github.com/symfony/maker-bundle/issues/987

**Comment by wouterj** [comment] 2021-10-16 12:34
Hi there! Thanks for reporting the issue.

This has been reported several times already and a fix has been merged (but not yet released) in https://github.com/symfony/maker-bundle/pull/991 It's often a great idea to check the recently reported issues before opening a new one - that saves you and us some time :)

**Closed by wouterj** 2021-10-16 12:34 UTC
