### ISSUE TITLE
'Make:entity' failed when don't use the default namespace 'App'.

### ISSUE THREAD

**Issue by yuhuaian** [symfony/maker-bundle#133] opened 2018-03-16 15:27 UTC
src/Doctrine/DoctrineEntityHelper.php
line 45
`$entityClassDetails = new ClassNameDetails($metadata->name, 'App\\Entity');`

src/Maker/MakeCommand.php
line 91
`$generator = new Generator($this->fileManager, 'App\\');`

**Comment by weaverryan** [comment] 2018-03-19 01:00
Hmm, the command should work if you pass a fully-qualified class name to the first step - e.g. `Acme\Foo\Bar`, but it looks like we missed at least one thing:

Here's the error I'm currently getting:

```
./bin/console make:entity

 Class name of the entity to create or update (e.g. GentleGnome):
 > \App\Foo\Bar\Entity\Baz

 created: src/Foo/Bar/Entity/Baz.php
 created: src/Repository/Foo/Bar/Entity/BazRepository.php

 [ERROR] Only annotation mapping is supported by make:entity, but the                            
         <info>App\Foo\Bar\Entity\Baz</info> class uses a different format. If you would like    
         this command to generate the properties & getter/setter methods, add your mapping       
         configuration, and then re-run this command with the <info>--regenerate</info> flag.    
```

**Comment by kilianklein** [comment] 2018-03-31 19:38
Hi guys, first of all thanks for this amazing and promising bundle!

I am testing the bundle with symfony3.4 (as the documentation mentioned it should work with it) and indeed I had to go mess directly with the 2 lignes @yuhuaian mentioned to change "App" to "AppBundle" (unless I am wrong this is the convention for the bundle name for 3.4?). Otherwise, I would not get prompted for the entity's fully qualified name and would get this error instead:

> Could not determine where to locate the new class "App\Entity\Test".

Hope this helps.

**Comment by weaverryan** [comment] 2018-04-02 21:15
Hmm, this does help! What you’re describing is the expected behavior: we assume App unless you pass a full class name (including the beginning slash iirc). But, I think if we guess App, but we can’t determine where to generate the file (which means that you have no App namespace in your autoloading), we could THEN ask you to clarify by entering the full class name. Then you could easily know how to use the command in these cases :).

**Comment by kilianklein** [comment] 2018-04-02 21:39
Thanks  for your answer, the solution sounds good to me! :)

**Comment by helariL** [comment] 2018-04-30 11:00
Wouldn't it be possible to reference namespace directly from composer.json ? If we anyway have to define it for autoload.

**Comment by upyx** [comment] 2018-05-03 13:02
Hello!

I have the similar issue. We don't use `App` as root namespace of our project so all `make:*` commands doesn't work. Few examples:

| Command | Error
| -- | --
| make:auth | Could not determine where to locate the new class "App\Security\SuperAuth".
| make:command | Could not determine where to locate the new class "App\Command\ProjHelloCommand".
| make:controller | Could not determine where to locate the new class "App\Controller\VictoriousGnomeController".
| make:entity | Could not determine where to locate the new class "App\Entity\TinyKangaroo".
| make:form | Could not determine where to locate the new class "App\Form\TinyPizzaType".
| make:functional-test | Could not determine where to locate the new class "App\Tests\DefaultControllerTest".
| make:unit-test | Could not determine where to locate the new class "App\Tests\UtilTest".

As we can see all errors are identical. It is because `App` is hardcoded and there is no way to change it without interfering to code. I'm not sure that simple determining root namespace is possible. But we can do it configurable.

I've found 8 places where `App` was hardcoded. So refactoring won't be very difficult.

What do you think about?

P.S.
What do you say about changing title to "All 'make:*' failed..."?

**Comment by weaverryan** [comment] 2018-05-03 19:40
@upyx Actually, your description isn't quite right, but clearly the bundle isn't doing a very helpful job :). You can use a non-App namespace on any command, but you must type the full class name. For example, you should be able to

```php
php bin/console make:controller
```

Then, when it asks you for the controller name, use:

> \MyNamespace\Controller\FooController

By starting your namespace with `\`, we know that you are giving us a full namespace.

We need to:

A) Give a better error message in all commands. Instead of `Could not determine where to locate the new class "App\Security\SuperAuth".`, we need to suggest that the user type in the full namespace, because obviously, `App\` is not used by them.

B) We probably need to make the `App\` root prefix configurable.

**Comment by LeJeanbono** [comment] 2018-05-03 22:52
Should we do a configuration file ?

**Comment by upyx** [comment] 2018-05-04 04:54
@weaverryan Oh, I didn't know that. Thank you for advice.
However not all commands ask class name. For example, `make:command` asks command name and doesn't ask class.
I think it would be better if a user does not need to type the full class name.

@LeJeanbono I think so. Would you like to do that?

**Comment by eugenekurasov** [comment] 2018-05-04 09:06
Is any news about repository in Make:entity?

I can do PR if needed.

**Comment by helariL** [comment] 2018-05-04 10:53
@upyx it was just a suggestion. 😄 Obviously configuration file would be the best option. To be honest I would be happy if we could even pass it in like other options ```--namespace=MyAwesomeApp\\src``` ( or something similar )

**Comment by eugenekurasov** [comment] 2018-05-04 11:01
@helariL You can use absolute path (https://github.com/symfony/maker-bundle/blob/master/src/Generator.php#L107)
```make:controller \\Controller\\CustomController ```

**Comment by helariL** [comment] 2018-05-04 11:13
@eugenekurasov yes that works really well when generating controllers etc. but try the same thing with make:entity 😉

**Comment by eugenekurasov** [comment] 2018-05-04 11:41
@helariL Make:entity has problem with absolute path.
I created [issue](https://github.com/symfony/maker-bundle/issues/168) for make:entity, but then closed.

**Comment by javiereguiluz** [comment] 2018-07-06 09:10
Closing as fixed by #173.

**Closed by javiereguiluz** 2018-07-06 09:10 UTC
Labels: bug

**Comment by kategray** [comment] 2020-01-18 03:58
I'm getting the same error, having configured the default namespace.  I'm using my own namespace under src/.

```
ubuntu@aerobill:/var/www/aerobill$ ./bin/console make:entity

 Class name of the entity to create or update (e.g. BraveElephant):
 > Tenant

 created: src/Entity/Tenant.php
 created: src/Repository/TenantRepository.php


 [ERROR] Only annotation mapping is supported by make:entity, but the <info>UberFlight\Entity\Tenant</info> class uses
         a different format. If you would like this command to generate the properties & getter/setter methods, add your
         mapping configuration, and then re-run this command with the <info>--regenerate</info> flag.
```
```
ubuntu@aerobill:/var/www/aerobill$ cat config/packages/dev/maker.yaml
maker:
    root_namespace: 'UberFlight'
```

**Comment by piotrkardasz** [comment] 2020-04-02 15:04
For People looking for answer:
 
It works! To clarify use config similar to this:

> config/packages/doctrine.yaml

``` yaml
doctrine:
    orm:
        mappings:
            YourAcme:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'YourAcme\Entity'
                alias: YourAcme
```

> config/packages/dev/maker.yaml

``` yaml
maker:
    root_namespace: YourAcme
```

**Comment by jonmnoj** [comment] 2020-06-13 02:16
If you are using 3.4 you need to place the maker config in
> app/config/config_dev.yml

**Comment by upyx** [comment] 2023-01-16 09:59
> What if I want to have multiple custom folders? (e.g YourAcme2, YourAcme3 etc) I will then have to change the root_namespace manually every time I want to create entity/repository for that specific folder. Is that right?

No. See https://github.com/symfony/maker-bundle/issues/133#issuecomment-374073278

You can set the full class name like:

```sh
bin/console make:entity '\YourAcme2\Entity\SomeEntity'
```
