### ISSUE TITLE
Duplicate `use` statement for certain types

### ISSUE THREAD

**Issue by kgrozdanovski** [symfony/maker-bundle#1171] opened 2022-08-30 19:54 UTC
When defining multiple properties via the Entity maker (`make:entity`) with the same type `datetime_immutable` the following error appears after the second property has been defined:

> In NameContext.php line 71:                                                                                            
>Cannot use DateTimeImmutable as DateTimeImmutable because the name is already in use on line 12 

**How to reproduce**

Simply run `make:entity <myEntity>` and define two consecutive properties with type `datetime_immutable`.

**Suggested fix**

Check if such a `use` statement already exists in the class in the `addUseStatementIfNecessary` function in the `ClassSourceManipulator.php` file.

**Comment by mdoutreluingne** [comment] 2022-09-03 08:35
I can't reproduce your issue, after creating 2 consecutive properties of the same type `datetime_immutable` in a new entity. This is what I did:

```text
php bin/console make:entity myEntity

 created: src/Entity/MyEntity.php
 created: src/Repository/MyEntityRepository.php
 
 Entity generated! Now let's add some fields!
 You can always add more fields later manually or by re-running this command.

 New property name (press <return> to stop adding fields):
 > date1

 Field type (enter ? to see all types) [string]:
 > datetime_immutable

 Can this field be null in the database (nullable) (yes/no) [no]:
 >

 updated: src/Entity/MyEntity.php

 Add another property? Enter the property name (or press <return> to stop adding fields):
 > date2                  

 Field type (enter ? to see all types) [string]:
 > datetime_immutable

 Can this field be null in the database (nullable) (yes/no) [no]:
 >

 updated: src/Entity/MyEntity.php
```

Symfony version: 6.2-dev
Maker bundle version: 1.45.0

**Comment by kgrozdanovski** [comment] 2022-09-03 10:47
My apologies, I forgot to note the package versions.

**Comment by mdoutreluingne** [comment] 2022-09-04 08:04
I still can't reproduce your issue with the same version as you. I have no problem generating 2 consecutive properties of the same type `datetime_immutable` in a new entity. Maybe someone else will be able to reproduce your issue.

**Comment by jrushlow** [comment] 2022-11-08 17:26
Howdy @kgrozdanovski I'm unable to reproduce the issue you're describing in either Maker `v1.45.0` w/ `5.4` && `8.1` or in the latest version of Symfony w/ the latest maker release.

But something that did catch my eye, when using `make:entity` and selecting a native PHP type, e.g. `datetime_immutable`, MakerBundle *does not* add a use statement for that as it uses the root namespace when using the type within a template. e.g. `\DateTimeImmutable` 

I'm going to close this issue for now, but if you're still having problems - please create a simple reproducer on GitHub that we can reference to further help you out. Thanks in advance!

**Closed by jrushlow** 2022-11-08 17:26 UTC
Labels: Bug, Unconfirmed, Status: Needs Review
