### ISSUE TITLE
[BUG] make:user breaks with PostgreSQL due to a conflict with the reserved keyword "user"

### ISSUE THREAD

**Issue by Aerendir** [symfony/maker-bundle#525] opened 2020-01-08 18:39 UTC
When using the command `make:user` the generated class is `Entity\User` that is like this:

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    ...
}
```

When using it, it causes a `PDOException`:

> Doctrine\\DBAL\\Exception\\InvalidFieldNameException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ?' with params [\"hello@example.com\"]:\n\nSQLSTATE[42703]: Undefined column: 7 ERROR: column t0.id does not exist\nLINE 1: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles...\n ^ in /Users/Aerendir/Documents/My/Project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 60

The problem is caused by the fact that the generated table is called `user`.

The word `user` in PostgreSQL is a reserved word.

More info about this in this answer on Stackoverflow: https://stackoverflow.com/questions/30157913/doctrine-column-id-does-not-exist-on-postgresql

The solution is to generate the `User` class naming the table `users` instead of leaving Doctrine itself call it `user`:

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="users")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    ...
}
```

**Comment by strawburrypokki** [comment] 2020-01-08 19:22
Hi!
Does quoting the table name solves the problem?

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
```

See doctrine docs for more info : https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words

**Comment by LeJeanbono** [comment] 2020-01-08 21:27
Hi,
duplicate of #485

**Comment by Aerendir** [comment] 2020-01-08 21:55
@strawburrypokki , yes, quoting solves the problem, but the entity is created by the command itself...

@LeJeanbono , sorry, I didn’t saw it 😅

**Closed** 2020-01-08 21:56 UTC
