### ISSUE TITLE
[idea/feature] Offer new Option

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/maker-bundle#594] opened 2020-04-23 08:48 UTC
***Description***

When you have symfony project with custom architecture you lost a part of powerfull maker bundle because directory isn't at the same place.

Actually i create a wrapper to do that [TwcMakerBundle](https://github.com/thewalkingcoder/maker-bundle) but may be is interesting to introduce this feature directly.

Before work to PR, do you think the idea/feature can help, or is out of context ?

@weaverryan WDYT ?

**Comment by jrushlow** [comment] 2021-02-16 09:27
this is a duplicate of #624 - im going to close this issue as its predecessor title is a bit more concise. Thanks @thewalkingcoder !

**Closed by jrushlow** 2021-02-16 09:27 UTC
Labels: duplicate
