### ISSUE TITLE
Maker Bundle fails to create ManyToMany relation

### ISSUE THREAD

**Issue by cybernet** [symfony/maker-bundle#329] opened 2018-12-12 10:34 UTC
**Maker version(s) affected**: 1.9
**Description**  
I tried to create a second ManyToMany relation on both mentioned symfony versions
PHP 7.2.13

**How to reproduce**  
`php bin/console make:entity`

 Class name of the entity to create or update (e.g. TinyGnome):
 > Members

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > maksim

 Field type (enter ? to see all types) [string]:
 > relation

 What class should this entity be related to?:
 > Ships

 Relation type? [ManyToOne, OneToMany, ManyToMany, OneToOne]:
 > ManyToMany

 Do you want to add a new property to Ships so that you can access/update Members objects from it - e.g. $ships->getMembers()? (yes/no) [yes]:
 >

 New field name inside Ships [members]:
 > maksim

**Error**  
[error] Error thrown while running command "make:entity". Message: "Syntax error, unexpected T_VARIABLE, expecting '(' on line 61"

```
In ParserAbstract.php line 314:

  Syntax error, unexpected T_VARIABLE, expecting '(' on line 61
```

**Comment by alexandrunastase** [comment] 2018-12-16 12:06
> I tried to create a second ManyToMany relation on both mentioned symfony versions

What are the Symfony versions ? I can't find any reference to them

I tried reproducing the issue using PHP 7.2, Symfony 4.2 and version 1.9 of the maker bundle, but could not produce the error you mentioned. 

  This might have been some issue with the php parser (nikic/php-parser), as that seems related to your error. Version 4.1.0 of the php-parser seems to work propertly, as I am using in my test project. Maybe upgrading to this version will fix your issue.

**Comment by cybernet** [comment] 2018-12-18 08:58
@alexandrunastase as mentioned on the issue, the reference ( https://github.com/symfony/symfony/issues/29580 ) symfony 4.1.9 , 4.2.1. does it help if i post the Entity ?

**Comment by alexandrunastase** [comment] 2018-12-18 19:20
@cybernet  Please do post the Entity. Were you updating it, or creating it from scratch ?

Please also post what version of the nikic/php-parser depedency you have in your composer.lock file

**Comment by cybernet** [comment] 2018-12-20 16:49
I tried to reproduce the bug again, and I can't ...
I reverted my entities to the original format ( before ManyToMany ) and still can't reproduce the bug ...
these are the [Entities](https://gist.github.com/cybernet/27625809103801f90d9559cb2f422cec) with multiple ManyToMany

the field that i tried to create with maker bundle is `ships` from `Ca` entity

**Comment by javiereguiluz** [comment] 2019-01-23 08:55
Let's close this because the bug is no longer happening. Thanks @alexandrunastase for your help with this issue!

**Closed by javiereguiluz** 2019-01-23 08:55 UTC

**Comment by Aracon** [comment] 2020-01-30 18:03
I have this bug when adding new field to the entity. 

Here is the console log:

```
>php bin/console make:entity

 Class name of the entity to create or update (e.g. GentleChef):
 > TransportCostRule

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > settingEntity

 Field type (enter ? to see all types) [string]:
 > relation

 What class should this entity be related to?:
 > Setting

What type of relationship is this?
 ------------ --------------------------------------------------------------------------------
  Type         Description

 ------------ --------------------------------------------------------------------------------
  ManyToOne    Each TransportCostRule relates to (has) one Setting.

               Each Setting can relate to (can have) many TransportCostRule objects


  OneToMany    Each TransportCostRule can relate to (can have) many Setting objects.
               Each Setting relates to (has) one TransportCostRule



  ManyToMany   Each TransportCostRule can relate to (can have) many Setting objects.
               Each Setting can also relate to (can also have) many TransportCostRule objects


  OneToOne     Each TransportCostRule relates to (has) exactly one Setting.

               Each Setting also relates to (has) exactly one TransportCostRule.

 ------------ --------------------------------------------------------------------------------

 Relation type? [ManyToOne, OneToMany, ManyToMany, OneToOne]:
 > ManyToOne

 Is the TransportCostRule.settingEntity property allowed to be null (nullable)? (yes/no) [yes]:
 > no

 Do you want to add a new property to Setting so that you can access/update TransportCostRule objects from it - e.g. $setting->getTransportCostRules()? (yes/no) [yes]:
 >

 A new property will also be added to the Setting class so that you can access the related TransportCostRule objects from it.

 New field name inside Setting [transportCostRules]:
 >

 Do you want to activate orphanRemoval on your relationship?
 A TransportCostRule is "orphaned" when it is removed from its related Setting.
 e.g. $setting->removeTransportCostRule($transportCostRule)

 NOTE: If a TransportCostRule may *change* from one Setting to another, answer "no".

 Do you want to automatically delete orphaned App\Entity\TransportCostRule objects (orphanRemoval)? (yes/no) [no]:
 > yes


In ParserAbstract.php line 315:

  Syntax error, unexpected T_VARIABLE, expecting '(' on line 61


make:entity [-a|--api-resource] [--regenerate] [--overwrite] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]
```

Entity: https://gist.github.com/Aracon/418af4c405bee420cb6aafaf5fcd87ff
Related entity: https://gist.github.com/Aracon/9c1d15391041fc4e6010a88af6b8b727
composer.lock: https://gist.github.com/Aracon/31c77c7ffce6fb6928e48952f6afd4ef

PHP  7.2.10

**Comment by larskoeie** [comment] 2021-02-03 16:05
I receive a slightly different error on creating a ManyToMany relation. I have created multiple MTM relations in the same setup previously.

```
15:45:37-lko/var/www/virtual/datahub-symfony4-lko/docs/datahub$ bin/console make:entity

 Class name of the entity to create or update (e.g. FiercePizza):
 > \Bolius\ContentBundle\Entity\ContentObject

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > images

 Field type (enter ? to see all types) [string]:
 > ManyToOne

 What class should this entity be related to?:
 > 
15:47:57-lko/var/www/virtual/datahub-symfony4-lko/docs/datahub$ bin/console make:entity

 Class name of the entity to create or update (e.g. VictoriousKangaroo):
 > \Bolius\ContentBundle\Entity\ContentObject

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > images

 Field type (enter ? to see all types) [string]:
 > ManyToMany

 What class should this entity be related to?:
 > \Bolius\ContentBundle\Entity\Image

 Do you want to add a new property to Image so that you can access/update ContentObject objects from it - e.g. $image->getContentObjects()? (yes/no) [yes]:
 > no


In ParserAbstract.php line 317:
                                                                             
  Syntax error, unexpected T_NS_SEPARATOR, expecting T_VARIABLE on line 261  
                                                                             

make:entity [-a|--api-resource] [--regenerate] [--overwrite] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]

```

PHP 7.2.24
Symfony 4.4
Maker-bundle 1.28.0

Hope the info is sufficient.
